/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BitBlockToken__factory } from "./BitBlockToken__factory";
export { EventContract__factory } from "./EventContract__factory";
