/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ApproveAndCallFallBack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ApproveAndCallFallBack__factory>;
    getContractFactory(
      name: "BitBlockToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BitBlockToken__factory>;
    getContractFactory(
      name: "ERC20Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Interface__factory>;
    getContractFactory(
      name: "EventContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventContract__factory>;
    getContractFactory(
      name: "SafeMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeMath__factory>;

    getContractAt(
      name: "ApproveAndCallFallBack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ApproveAndCallFallBack>;
    getContractAt(
      name: "BitBlockToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BitBlockToken>;
    getContractAt(
      name: "ERC20Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Interface>;
    getContractAt(
      name: "EventContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventContract>;
    getContractAt(
      name: "SafeMath",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeMath>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
