/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ApproveAndCallFallBack,
  ApproveAndCallFallBackInterface,
} from "../ApproveAndCallFallBack";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokens",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "receiveApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ApproveAndCallFallBack__factory {
  static readonly abi = _abi;
  static createInterface(): ApproveAndCallFallBackInterface {
    return new utils.Interface(_abi) as ApproveAndCallFallBackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ApproveAndCallFallBack {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ApproveAndCallFallBack;
  }
}
